title: Yongcheng Wu
subtitle: Physcis Nerd
description: Website and portfolio of YC WU

author: Yongcheng Wu
email: niepanchongsheng@126.com
avatar: assets/images/avatar.jpg

baseurl: "https://zhangyan232425.github.io"
url: "https://zhangyan232425.github.io"

# Social settings
facebook_url: https://www.facebook.com/chris.bobbe
github_url: https://github.com/chrisbobbe
linkedin_url: https://www.linkedin.com/in/chrisbobbe1995/
twitter_url: https://twitter.com/chrisbobbe

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
